name: Deploy Website

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  deploy-staging:
    name: "Deploy staging branch"
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up PHP
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "latest"
      - name: Install dependencies through Composer
        uses: "ramsey/composer-install@v3"
      - name: "Deploy"
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "sftp"
          remote-host: ${{ vars.HOST }}
          remote-user: ${{ vars.USERNAME }}
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}
          remote-path: ${{ vars.PATH }}
          sync-delta-includes: "vendor"
